---
# Get checksum for node_exporter
- name: Get checksum for node_exporter
  delegate_to: localhost
  run_once: true
  block:
    - name: Get checksum list from github
      ansible.builtin.set_fact:
        __node_exporter_checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter__version + '/sha256sums.txt', wantlist=True) | list }}"
    - name: "Get checksum for amd64 architecture"
      ansible.builtin.set_fact:
        node_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __node_exporter_checksums }}"
      when:
        - "('linux-' + 'amd64' + '.tar.gz') in item"

# Get latest node-exporter binary
- name: Get latest node-exporter binary
  block:
    - name: Download node_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter__version }}/node_exporter-{{ node_exporter__version }}.linux-amd64.tar.gz"
        dest: "{{ node_exporter__tmp_dir }}/node_exporter-{{ node_exporter__version }}.linux-amd64.tar.gz"
        checksum: "sha256:{{ node_exporter_checksum }}"
        mode: 0644
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack node_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ node_exporter__tmp_dir }}/node_exporter-{{ node_exporter__version }}.linux-amd64.tar.gz"
        dest: "{{ node_exporter__tmp_dir }}"
        creates: "{{ node_exporter__tmp_dir }}/node_exporter-{{ node_exporter__version }}.linux-amd64/node_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate node_exporter binaries
      ansible.builtin.copy:
        src: "{{ node_exporter__tmp_dir }}/node_exporter-{{ node_exporter__version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter__path }}"
        mode: 0755
        owner: root
        group: root
      notify: Restart node_exporter
      when: not ansible_check_mode

# Create group for node_exporter
- name: Create Node Exporter user and group
  when: node_exporter__system_user != "root"
  block:
    - name: Create the node_exporter group
      ansible.builtin.group:
        name: "{{ node_exporter__system_group }}"
        state: present
        system: true
    # Create user for node_exporter
    - name: Create the node_exporter user
      ansible.builtin.user:
        name: "{{ node_exporter__system_user }}"
        groups: "{{ node_exporter__system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
