---
# Check current installed version
- name: Gather currently installed node_exporter version (if any)
  ansible.builtin.command: node_exporter --version
  register: node_exporter_current_version
  failed_when: false
  changed_when: false
  check_mode: false


# Get last version from github
- name: Get latest Node Exporter version from github.
  when:
    - node_exporter__version == "latest" 
  delegate_to: localhost
  run_once: true
  become: false
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: False
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: latest_node_exporter_version
      until: latest_node_exporter_version.status == 200
      retries: 5

    - name: "Set node_exporter version to {{ latest_node_exporter_version.json.tag_name[1:] }}"
      ansible.builtin.set_fact:
        node_exporter__version: "{{ latest_node_exporter_version.json.tag_name[1:] }}"
